---
- name: Playbook
  hosts: all
  become: yes

  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common    

  tasks:
  - name: Docker installation - installing prerequisites
    ansible.builtin.apt:
      name: "{{item}}"
      update_cache: yes
    with_items: 
      - "{{packages}}"

  - name: Docker installation - Adding apt-key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Docker installation - Adding docker repo
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable
      state: present
      update_cache: yes

  - name: Update cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Docker installation - Installing Docker
    ansible.builtin.apt:
      name:
        - docker.io
        - docker-ce-cli
        - containerd.io
      update_cache: yes
