---
- name: Playbook
  hosts: all
  become: yes

  - name: Apache installation
    ansible.builtin.apt:
      name:
        - apache2
      update_cache: yes

  - name: Start service
    ansible.builtin.service:
      name: apache2
      state: started
